### ISSUE TITLE
should we transfer this to the Istanbul org?

### ISSUE THREAD

**Issue by bcoe** [istanbuljs/spawn-wrap#24]
I think this library is mainly used by `nyc` should we consider transferring this to the Istanbuljs org?

`signal-exit`, and `foreground-child` are used by `node-tap`, so perhaps we should leave them in this organization? an other option is we don't move any of the modules, your call @isaacs.

CC: @gotwarlost?

**Comment by gotwarlost** [comment]
No opinions. Either way works for me.
