### ISSUE TITLE
spawn-wrap test on windows & Appveyor failing

### ISSUE THREAD

**Issue by BurtHarris** [istanbuljs/spawn-wrap#55]
Latest appveyor results show this failing on Windows   https://ci.appveyor.com/project/isaacs/spawn-wrap

I'm guessing that may be a contributing factor to isaacs/isexe#13

**Comment by mykmelez** [comment]
> I'm guessing that may be a contributing factor to isaacs/isexe#13

This one looks like #56, which I've fixed in #57. It's possible that PR also fixes the test failures on Appveyor, although I'm still seeing test failures locally on Windows.

**Comment by mykmelez** [comment]
I've now fixed these failures in #57.

**Comment by BurtHarris** [comment]
It looks like the latest Appveyor failure is only on NodeJS v 0.12, and that an incompatibility between that version and NPM 5.0.4 may be to blame.   

Perhaps it's time to drop support for NodeJS 0.12.

**Comment by mykmelez** [comment]
@isaacs fixed this in https://github.com/tapjs/spawn-wrap/commit/393f800d99551ba8468cc7e391a5a5270760c693 and https://github.com/tapjs/spawn-wrap/commit/2921d648108b555089f2e71362d1b54d2ab4d568.

**Comment by demurgos** [comment]
This issue can be closed, Windows tests are working right now. (#82).

/cc @coreyfarrell

**Comment by coreyfarrell** [comment]
Thanks for the ping.
