### ISSUE TITLE
spawn-wrap fails fails to shim node on Windows (part deux)

### ISSUE THREAD

**Issue by jasongardnerlv** [istanbuljs/spawn-wrap#56]
see #43 

The code change made for that issue is case sensitive and only fixes this for ".exe".  I'm running on Windows 10 in babun/cygwin, and my error is:

`
Error: Cannot find module 'C:\Users\<username>\.node-spawn-wrap-99436-4aa667b29537\node.EXE'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
`

Looks like `path.basename` itself is case-sensitive, so a different solution is necessary:
[https://github.com/jinder/path/blob/master/path.js#L353](https://github.com/jinder/path/blob/master/path.js#L353)

**Comment by mykmelez** [comment]
> Looks like path.basename itself is case-sensitive, so a different solution is necessary:
> https://github.com/jinder/path/blob/master/path.js#L353

That's an old version of the path module, but the latest version also looks case-sensitive (albeit without a comment questioning that behavior on Windows):

https://github.com/nodejs/node/blob/master/lib/path.js#L817-L904

**Comment by mykmelez** [comment]
I filed https://github.com/nodejs/node/issues/13727 on the issue in Node.

**Comment by mykmelez** [comment]
@isaacs fixed this in https://github.com/tapjs/spawn-wrap/commit/fc98d38664c364cc55588e39de747aef03d767ea.
